import boxPresente from '@/ativos/produtos/box-presente.jpg';
import imgPolaroide from '@/ativos/subcat-polaroide.png';
import imgPolaroidMini1 from '@/ativos/produtos/PolaroidMini1.png';
import imgPolaroidMini2 from '@/ativos/produtos/PolaroidMini2.png';
import imgPolaroidClassica1 from '@/ativos/produtos/PolaroidClassica1.png';
import imgPolaroidClassica2 from '@/ativos/produtos/PolaroidClassica2.png';
import imgPolaroidGrande1 from '@/ativos/produtos/PolaroidGrande1.png';
import imgPolaroidGrande2 from '@/ativos/produtos/PolaroidGrande2.png';
import imgA5 from '@/ativos/subcat-a5.png';
import imgA4 from '@/ativos/subcat-a4.png';
import imgSacolaGeneric from '@/ativos/subcat-sacola-generic.png';
import imgSacolaVertical from '@/ativos/subcat-sacola-vertical.jpg';
import imgSacolaHorizontal from '@/ativos/subcat-sacola-horizontal.jpg';
import imgSacolaAlmofada from '@/ativos/subcat-sacola-almofada.jpg';
import imgCaixaPiramide from '@/ativos/subcat-caixa-piramide.png';
import imgCaixaMilk1 from '@/ativos/produtos/CaixaMilk1.png';
import imgCaixa10x9_1 from '@/ativos/produtos/Caixa10x9_1.png';
import imgEtiquetaGeneric from '@/ativos/subcat-etiqueta-generic.png';
import imgCaixa15x13x4 from '@/ativos/caixa-15-13-4-2.png';
import imgCaixa15x13x4_1 from '@/ativos/caixa-15-13-4-1.png';
import imgChaveiroRedondo from '@/ativos/produtos/ChaveiroRedondo.png';
import imgChaveiroRedondo2 from '@/ativos/produtos/ChaveiroRedondo2.png';
import imgChaveiroQuadrado1 from '@/ativos/produtos/ChaveiroQuadrado1.jpg';
import imgChaveiroQuadrado2 from '@/ativos/produtos/ChaveiroQuadrado2.jpg';
import imgChaveiroCereja from '@/ativos/ChaveiroCereja.png';
import imgCartaoGeneric from '@/ativos/subcat-cartao-generic.png';
import imgCartaoVisita1 from '@/ativos/produtos/CartaoVisita1.jpg';
import imgCartaoVisita2 from '@/ativos/produtos/CartaoVisita2.png';
import imgCartaoAgradecimento from '@/ativos/produtos/CartaoAgradecimento.png';
import imgCartaoFidelidade from '@/ativos/produtos/CartaoFidelidade.jpg';
import imgSacola18x21_1 from '@/ativos/sacola-18-21-1.png';
import imgSacola18x21_2 from '@/ativos/sacola-18-21-2.png';
import imgSacola18x21_3 from '@/ativos/sacola-18-21-3.png';
import imgSacola18x21_Kraft_1 from '@/ativos/sacola-18-21-kraft-1.png';
import imgSacola18x21_Kraft_2 from '@/ativos/sacola-18-21-kraft-2.png';
import imgSacola11x8_1 from '@/ativos/sacola-11-8-1.png';
import imgSacola11x8_2 from '@/ativos/sacola-11-8-2.png';
import imgSacola15x11_1 from '@/ativos/sacola-15-11-1.png';
import imgSacola15x11_2 from '@/ativos/sacola-15-11-2.png';
import imgCaixa9x4x2_1 from '@/ativos/caixa-9-4-2-1.png';
import imgCaixa9x4x2_2 from '@/ativos/caixa-9-4-2-2.png';
import imgEtiquetaCaixao from '@/ativos/EtiquetaCaixao.png';
import imgEtiquetaQuadrada1 from '@/ativos/produtos/EtiquetaQuadrada1.png';
import imgEtiquetaQuadrada2 from '@/ativos/produtos/EtiquetaQuadrada2.png';
import imgAdesivoRedondo1 from '@/ativos/AdesivoRedondo1.png';
import imgAdesivoRedondo2 from '@/ativos/AdesivoRedondo2.png';
import imgAdesivoRedondo3 from '@/ativos/AdesivoRedondo3.png';
import imgAdesivoTransparente from '@/ativos/AdesivoRedondoTransparente.png';
import imgAdesivoQuadrado from '@/ativos/produtos/AdesivoQuadrado.png';
import imgAdesivoQuadradoTransparente from '@/ativos/produtos/AdesivoQuadradoTransparente.png';
import imgCartaoPresente from '@/ativos/produtos/CartaoPresente.jpg';
import imgPolaroideDeMesa1 from '@/ativos/produtos/PolaroideDeMesa1.png';
import imgFoto3x4_1 from '@/ativos/produtos/Foto3x4_1.jpg';
import imgFoto3x4_2 from '@/ativos/produtos/Foto3x4_2.jpg';
import imgFoto10x15_1 from '@/ativos/produtos/Foto10x15_1.jpg';
import imgFoto10x15_2 from '@/ativos/produtos/Foto10x15_2.jpg';
import imgFotoA5_1 from '@/ativos/produtos/FotoA5_1.jpg';
import imgFotoA5_2 from '@/ativos/produtos/FotoA5_2.jpg';
import imgFotoA4_1 from '@/ativos/produtos/FotoA4_1.jpg';
import imgFotoA4_2 from '@/ativos/produtos/FotoA4_2.jpg';
import imgLabelRound1 from '@/ativos/produtos/label_round_1.png';
import imgLabelRound2 from '@/ativos/produtos/label_round_2.png';
import imgLabelRound3 from '@/ativos/produtos/label_round_3.png';
import imgLabelRect1 from '@/ativos/produtos/label_rect_1.png';
import imgLabelRect2 from '@/ativos/produtos/label_rect_2.png';
import imgLabelRect3 from '@/ativos/produtos/label_rect_3.png';
import imgIdentidadeVisualSamira from '@/ativos/produtos/IdentidadeVisualSamira.png';
import imgLogoDianaSantos from '@/ativos/produtos/LogoDianaSantos.png';
import imgLogoSolangeAlves from '@/ativos/produtos/LogoSolangeAlves.png';
import imgLogoKatiaNunes from '@/ativos/produtos/LogoKatiaNunes.png';
import imgCalendarioMini1 from '@/ativos/produtos/CalendarioMini1.jpg';
import imgCalendarioMini2 from '@/ativos/produtos/CalendarioMini2.png';
import imgCalendarioA4_1 from '@/ativos/produtos/CalendarioA4_1.jpg';
import imgCalendarioA4_2 from '@/ativos/produtos/CalendarioA4_2.png';
import imgBuqueBorboletas from '@/ativos/subcat-buque-borboletas.jpg';
import imgBuqueVanGogh from '@/ativos/subcat-buque-vangogh.jpg';
import imgImaGeladeira1 from '@/ativos/produtos/ImaGeladeira1.jpg';
import imgImaGeladeira2 from '@/ativos/produtos/ImaGeladeira2.jpg';
import imgConviteInterativo1 from '@/ativos/produtos/ConviteInterativo1.jpg';
import imgConviteInterativo2 from '@/ativos/produtos/ConviteInterativo2.jpg';
import imgConviteInterativo3 from '@/ativos/produtos/ConviteInterativo3.jpg';
import imgCaixaMilk from '@/ativos/subcat-caixa-milk.jpg';
import imgCaixaMaletinha from '@/ativos/subcat-caixa-maletinha.jpg';
import imgCaixaDocinho from '@/ativos/subcat-caixa-docinho.jpg';
import imgCaixaCanudo from '@/ativos/subcat-caixa-canudo.jpg';
import imgCaixaLanchinho from '@/ativos/subcat-caixa-lanchinho.jpg';
import imgCaixaPortaCaneta from '@/ativos/subcat-caixa-porta-caneta.jpg';
import imgCaixaPortaChaveiro from '@/ativos/subcat-caixa-porta-chaveiro.jpg';
import imgCaixaAlmofada from '@/ativos/subcat-caixa-almofada.jpg';
import imgCaixaCenario from '@/ativos/subcat-caixa-cenario.jpg';
import imgCaixaPortaSabonete from '@/ativos/subcat-caixa-porta-sabonete.jpg';
import imgCaixaCubo from '@/ativos/subcat-caixa-cubo.jpg';
import imgCaixaCachepo from '@/ativos/subcat-caixa-cachepo.jpg';
import imgCaixaCentroMesa from '@/ativos/subcat-caixa-centro-mesa.jpg';
import imgCaixaPortaBis from '@/ativos/subcat-caixa-porta-bis.jpg';
import imgCaixaMcDonalds from '@/ativos/subcat-caixa-mcdonalds.jpg';
import imgCaixaPortaTubete from '@/ativos/subcat-caixa-porta-tubete.png';
import imgTagXuxinha from '@/ativos/subcat-tag-xuxinha.png';
import imgConviteVideo from '@/ativos/subcat-convite-video.png';
import imgConviteDigital from '@/ativos/subcat-convite-digital.png';
import imgConviteInterativoSub from '@/ativos/subcat-convite-interativo.jpg';
import imgConvitePdfLongo from '@/ativos/subcat-convite-pdf-longo.jpg';
import imgConviteIndividualSub from '@/ativos/subcat-convite-individual.jpg';
import imgCofre from '@/ativos/subcat-cofre.png';
import imgApliqueTubete from '@/ativos/subcat-aplique-tubete.png';
import imgKitCorporativo from '@/ativos/subcat-kit-corporativo.jpg';
import imgKitFesta from '@/ativos/subcat-kit-festa.jpg';
import imgPortaDocinho from '@/ativos/subcat-porta-docinho.jpg';
import imgLivreto from '@/ativos/subcat-livreto.jpg';
import imgCaderno from '@/ativos/subcat-caderno.jpg';
import imgLambeLambe from '@/ativos/subcat-lambe-lambe.jpg';
import imgCadernoEspiral from '@/ativos/subcat-caderno-espiral.jpg';
import imgCadernoA5 from '@/ativos/subcat-caderno-a5.jpg';

export interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  category: string;
  subcategory?: string;
  image: string;
  images?: string[];
  kraftImages?: string[];
  isNew?: boolean;
  isFeatured?: boolean;
  variations?: { name: string; price: number }[];
  secondaryVariations?: { name: string; price: number }[];
  secondaryVariationTitle?: string;
  minQuantity?: number;
  noPaper?: boolean;
  volumeDiscounts?: { quantity: number; discount: number }[];
}

export const products: Product[] = [
  {
    id: 200,
    name: 'Polaroide Personalizada',
    description: 'Eternize momentos com música, frases e muito amor!',
    price: 2.00,
    category: 'dia-dos-namorados',
    subcategory: 'polaroide-personalizada',
    image: '/images/polaroide amor.jpeg',
    isNew: true,
    isFeatured: true,
    noPaper: true,
    variations: [
      { name: 'Mini', price: 2.00 },
      { name: 'Média', price: 3.50 },
      { name: 'Grande', price: 5.50 },
    ],
    secondaryVariationTitle: 'Personalização:',
    secondaryVariations: [
      { name: 'Padrão', price: 0 },
      { name: 'Código Spotify', price: 0 },
      { name: 'Frase Curta', price: 0 },
      { name: 'Data Especial', price: 0 },
      { name: 'Moldura Temática', price: 0 },
    ],
    volumeDiscounts: [
      { quantity: 10, discount: 3.00 }
    ]
  },
  {
    id: 227,
    name: 'Polaroide com Card',
    description: 'Linda polaroide com card personalizado.',
    price: 8.00,
    category: 'dia-dos-namorados',
    subcategory: 'polaroide-personalizada',
    image: '/images/polaroide com card.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 201,
    name: 'Álbum Personalizado',
    description: 'Cada figurinha é um momento especial para guardar!',
    price: 55.00,
    category: 'dia-dos-namorados',
    subcategory: 'album-copa-love',
    image: '/images/album da copa love.jpeg',
    isNew: true,
    isFeatured: true,
    noPaper: true,
    variations: [
      { name: '26 fotos', price: 55.00 },
      { name: '36 fotos', price: 65.00 },
    ],
  },
  {
    id: 202,
    name: 'Livro personalizado',
    description: 'Sete formas lindas de dizer eu te amo. Um presente do coração.',
    price: 40.00,
    category: 'dia-dos-namorados',
    subcategory: 'livro-personalizado',
    image: '/images/maarvel.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Marvel', price: 40.00 },
      { name: 'Disney', price: 40.00 },
      { name: 'Cars', price: 40.00 },
    ],
  },
  {
    id: 209,
    name: 'Amor para Colorir',
    description: 'Um presente interativo para colorir a sua história com todo amor.',
    price: 15.00,
    category: 'dia-dos-namorados',
    subcategory: 'love-goods',
    image: '/images/love goods.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: '8 páginas', price: 15.00 },
      { name: '14 páginas', price: 20.00 },
    ],
  },
  {
    id: 203,
    name: 'Caneca personalizada',
    description: 'Um café quentinho e todo o meu carinho para você.',
    price: 30.00,
    category: 'dia-dos-namorados',
    subcategory: 'caneca-acrilico',
    image: '/images/caneca.jpeg',
    isNew: true,
    noPaper: true,
    secondaryVariationTitle: 'Cor da Caneca:',
    secondaryVariations: [
      { name: 'Branca', price: 0 },
      { name: 'Preta', price: 0 },
      { name: 'Rosa', price: 0 },
      { name: 'Vermelho', price: 0 },
    ],
  },
  {
    id: 204,
    name: 'Quadros Personalizados',
    description: 'Eternize momentos especiais com todo o amor.',
    price: 25.00,
    category: 'dia-dos-namorados',
    subcategory: 'quadros-personalizados',
    image: '/images/quadro.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: '10x15 - Com Moldura', price: 25.00 },
      { name: '10x15 - Com Apoio (Sem Moldura)', price: 20.00 },
      { name: '14x21 - Com Moldura', price: 35.00 },
      { name: '14x21 - Com Apoio (Sem Moldura)', price: 30.00 },
      { name: '21x29 - Com Moldura', price: 55.00 },
      { name: '21x29 - Com Apoio (Sem Moldura)', price: 50.00 },
    ],
    secondaryVariationTitle: 'Escolha o Tema:',
    secondaryVariations: [
      { name: 'Spotify', price: 0 },
      { name: 'Ilustração', price: 0 },
      { name: 'Caricatura', price: 0 },
      { name: 'Montagem', price: 0 },
      { name: 'Netflix', price: 0 },
    ],
  },
  {
    id: 205,
    name: 'Polaroide de Mesa',
    description: 'Amor em destaque para decorar seu cantinho especial.',
    price: 15.00,
    category: 'dia-dos-namorados',
    subcategory: 'quadros-personalizados',
    image: '/images/pola mesa.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 206,
    name: '12 Motivos para te Amar',
    description: '12 motivos, 12 fotos para celebrar nosso amor!',
    price: 20.00,
    category: 'dia-dos-namorados',
    subcategory: '12-motivos',
    image: '/images/12 motibos.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 207,
    name: 'Vinho Personalizado',
    description: 'Um brinde ao nosso amor! (Escolha de marca sujeita a alteração de valores).',
    price: 80.00,
    category: 'dia-dos-namorados',
    subcategory: 'vinho-personalizado',
    image: '/images/vinho.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Vinho Rosé', price: 80.00 },
      { name: 'Vinho Branco', price: 80.00 },
      { name: 'Vinho Tinto', price: 80.00 },
    ],
  },
  {
    id: 208,
    name: 'Cartão Google',
    description: 'Pesquisei no Google e o resultado foi: o meu amor por você é infinito!',
    price: 8.00,
    category: 'dia-dos-namorados',
    subcategory: 'cartao-google',
    image: '/images/google.jpeg',
    isNew: true,
    variations: [
      { name: 'Tamanho P', price: 8.00 },
      { name: 'Tamanho M', price: 12.00 },
      { name: 'Tamanho G', price: 18.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Offset (Fosco comum)', price: 0 },
      { name: 'Matte (Fosco especial)', price: 0 },
      { name: 'Glossy (Brilho fotográfico)', price: 0 },
    ],
  },
  {
    id: 210,
    name: 'Chaveiro de Amor',
    description: 'Um detalhe especial para carregar seu amor sempre com você.',
    price: 12.00,
    category: 'dia-dos-namorados',
    subcategory: 'chaveiro-personalizado',
    image: '/images/chaveiro.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: '1 Chaveiro', price: 12.00 },
      { name: '2 Chaveiros', price: 20.00 },
    ],
  },
  {
    id: 211,
    name: 'Carrinho Hotwheels Personalizado',
    description: 'Carrinho personalizado com a foto do casal. Um presente épico!',
    price: 50.00,
    category: 'dia-dos-namorados',
    subcategory: 'hotwheels-personalizado',
    image: '/images/hotweels.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 212,
    name: 'Caixa de Bombom Personalizada',
    description: 'Uma caixa deliciosa e personalizada com os bombons favoritos do seu amor.',
    price: 35.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixa-bombom',
    image: '/images/WhatsApp Image 2026-05-10 at 19.00.08.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Garoto', price: 35.00 },
      { name: 'Nestlé', price: 40.00 },
      { name: 'Lacta', price: 40.00 },
    ],
  },
  {
    id: 213,
    name: 'Caixa Cascata',
    description: 'Uma cascata de lembranças para surpreender quem você ama!',
    price: 18.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixa-cascata',
    image: '/images/cascata.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: '5 fotos', price: 18.00 },
      { name: '10 fotos', price: 25.00 },
      { name: '15 fotos', price: 40.00 },
    ],
  },
  {
    id: 214,
    name: 'Caixa Explosão',
    description: 'Uma explosão de amor e surpresas em cada detalhe!',
    price: 50.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixa-explosao',
    image: '/images/explosao.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 215,
    name: 'Caixa Cenário',
    description: 'Um cenário romântico encantador para presentear quem você ama.',
    price: 25.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixa-cenario',
    image: '/images/cenario.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Caixa Vazia', price: 25.00 },
      { name: 'Com Guloseimas', price: 60.00 },
    ],
  },
  {
    id: 216,
    name: 'Vela Personalizada',
    description: 'Ilumine o coração de quem você ama com nossas velas aromáticas.',
    price: 12.00,
    category: 'dia-dos-namorados',
    subcategory: 'vela-personalizada',
    image: '/images/vela.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Kit com 4 velas', price: 12.00 },
      { name: 'Kit com 6 velas', price: 18.00 },
      { name: 'Kit com 8 velas', price: 25.00 },
      { name: 'Kit com 10 velas', price: 32.00 },
    ],
  },
  {
    id: 400,
    name: 'Jornal Personalizado',
    description: 'A notícia principal do dia: eu amo você! Nossa história em formato de jornal.',
    price: 30.00,
    category: 'dia-dos-namorados',
    subcategory: 'jornal-personalizado',
    image: '/images/jornal.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: '2 páginas', price: 30.00 },
      { name: '4 páginas', price: 50.00 },
    ],
  },
  {
    id: 401,
    name: 'Manual dos Padrinhos',
    description: 'Um guia especial para os seus padrinhos. Disponível em formato impresso ou digital.',
    price: 5.00,
    category: 'casamento',
    subcategory: 'manual-padrinhos',
    image: '/images/manual.jpg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Impresso (A partir de)', price: 5.00 },
      { name: 'Digital PDF (Incluso Padrinho/Madrinha)', price: 45.00 },
    ],
  },
  {
    id: 402,
    name: 'Convite Tradicional',
    description: 'Elegância para o seu grande dia. (Selecionar no ato da compra)',
    price: 5.00,
    category: 'casamento',
    subcategory: 'convite-tradicional',
    image: '/images/conv casam.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Tamanho 10x15', price: 5.00 },
      { name: 'Tamanho 10x20', price: 7.00 },
      { name: 'Tamanho 15x20', price: 10.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Couchê Brilho', price: 0 },
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Fotográfico Matte (Fosco)', price: 0 },
      { name: 'Fotográfico Glossy (Brilho)', price: 0 },
      { name: 'Offset', price: 0 },
      { name: 'Kraft', price: 0 },
    ],
  },
  {
    id: 403,
    name: 'Convite Individual',
    description: 'Complemento indispensável para o seu convite. (Selecionar no ato da compra)',
    price: 1.50,
    category: 'casamento',
    subcategory: 'convite-individual',
    image: imgConviteIndividualSub,
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Tamanho 5x5cm', price: 1.50 },
      { name: 'Tamanho 7x7cm', price: 2.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Offset (Fosco)', price: 0 },
      { name: 'Matte (Especial)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
    ],
  },
  {
    id: 404,
    name: 'Lágrimas de Alegria',
    description: 'Lenços personalizados para momentos emocionantes. (Selecionar no ato da compra)',
    price: 35.00,
    category: 'casamento',
    subcategory: 'lagrimas-alegria',
    image: '/images/lagrimas.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Kit 25un - Completo (Lenço + Embalagem)', price: 35.00 },
      { name: 'Kit 25un - Apenas Embalagem (Sem Lenço)', price: 27.00 },
      { name: 'Kit 50un - Completo (Lenço + Embalagem)', price: 65.00 },
      { name: 'Kit 50un - Apenas Embalagem (Sem Lenço)', price: 57.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Offset', price: 0 },
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Couchê Brilho', price: 0 },
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Kraft', price: 0 },
    ],
  },
  {
    id: 412,
    name: 'Convite Altar',
    description: 'Convite especial para o altar, disponível em diversos papéis e tamanhos.',
    price: 5.00,
    category: 'casamento',
    subcategory: 'convite-altar',
    image: '/images/convite altar.jpeg',
    isNew: true,
    variations: [
      { name: 'Tamanho 10x15', price: 5.00 },
      { name: 'Tamanho 14x20', price: 8.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Couchê Brilho', price: 0 },
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Kraft', price: 0 },
    ],
  },
  {
    id: 413,
    name: 'Tag Bem Casado',
    description: 'Tags personalizadas para bem-casados, disponíveis em diversos tamanhos e formatos.',
    price: 2.00,
    category: 'casamento',
    subcategory: 'tag-bem-casado',
    image: '/images/bem casado.jpeg',
    isNew: true,
    variations: [
      { name: 'Tamanho 5x5', price: 2.00 },
      { name: 'Tamanho 6x6', price: 2.50 },
      { name: 'Tamanho 7x7', price: 3.00 },
    ],
    secondaryVariationTitle: 'Formato e Acabamento:',
    secondaryVariations: [
      { name: 'Redondo - Com Furo', price: 0 },
      { name: 'Redondo - Sem Furo', price: 0 },
      { name: 'Quadrado - Com Furo', price: 0 },
      { name: 'Quadrado - Sem Furo', price: 0 },
    ],
  },
  {
    id: 414,
    name: 'Vale Conforto',
    description: 'Vale conforto personalizado para garantir o descanso dos seus convidados.',
    price: 3.00,
    category: 'casamento',
    subcategory: 'vale-conforto',
    image: '/images/vale conforto.jpeg',
    isNew: true,
    variations: [
      { name: 'Tamanho 7x7', price: 3.00 },
      { name: 'Tamanho 8x8', price: 4.00 },
      { name: 'Tamanho 9x9', price: 5.00 },
    ],
    secondaryVariationTitle: 'Formato:',
    secondaryVariations: [
      { name: 'Redondo', price: 0 },
      { name: 'Quadrado', price: 0 },
      { name: 'Retângulo', price: 0 },
      { name: 'Chinelo', price: 0 },
    ],
  },
  {
    id: 415,
    name: 'Save the Date',
    description: 'Arquivo digital personalizado para o seu grande dia.',
    price: 15.00,
    category: 'casamento',
    subcategory: 'save-the-date',
    image: '/images/save the date.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 416,
    name: 'Convite Digital',
    description: 'Convite digital personalizado disponível em diversos modelos.',
    price: 25.00,
    category: 'casamento',
    subcategory: 'convite-digital',
    image: '/images/convite digital.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Convite Simples', price: 25.00 },
      { name: 'Interativo Simples', price: 35.00 },
      { name: 'Convite Infinito', price: 60.00 },
    ],
  },
  {
    id: 405,
    name: 'Placa Pix',
    description: 'Facilite o presente com estilo e QR Code. (Selecionar no ato da compra)',
    price: 15.00,
    category: 'casamento',
    subcategory: 'placa-pix',
    image: '/images/placa pix.jpeg',
    isNew: true,
    noPaper: true,
  },

  {
    id: 410,
    name: 'Convite Padrinhos',
    description: 'Um convite especial para quem você ama. (Selecionar no ato da compra)',
    price: 6.00,
    category: 'casamento',
    subcategory: 'convite-padrinhos',
    image: '/images/caixa padr.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Impresso 10x15cm', price: 6.00 },
      { name: 'Impresso 14x21cm', price: 9.50 },
      { name: 'Digital (PDF)', price: 18.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Glossy (Brilho) Adesivo', price: 0 },
      { name: 'Kraft', price: 0 },
      { name: 'Couchê Brilho', price: 0 },
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Matte (Fosco)', price: 0 },
    ],
  },
  {
    id: 408,
    name: 'Envelope',
    description: 'O acabamento perfeito. (Selecionar no ato da compra)',
    price: 3.00,
    category: 'casamento',
    subcategory: 'convite-tradicional',
    image: '/images/envelope.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Para Convite 10x15', price: 3.00 },
      { name: 'Para Convite 10x20', price: 5.00 },
      { name: 'Para Convite 15x20', price: 7.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Offset', price: 0 },
      { name: 'Kraft', price: 0 },
      { name: 'Couchê', price: 0 },
      { name: 'Papel Linho', price: 6.00 },
      { name: 'Papel Vegetal', price: 5.00 },
    ],
  },
  {
    id: 409,
    name: 'Lacre de Cera',
    description: 'Toque clássico e artesanal. (Selecionar no ato da compra)',
    price: 18.00,
    category: 'casamento',
    subcategory: 'convite-tradicional',
    image: '/images/lacres.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Kit 5 unidades', price: 18.00 },
      { name: 'Kit 20 unidades', price: 38.00 },
      { name: 'Kit 30 unidades', price: 53.00 },
      { name: 'Kit 40 unidades', price: 68.00 },
    ],
    secondaryVariationTitle: 'Cor do Lacre:',
    secondaryVariations: [
      { name: 'Dourado', price: 0 },
      { name: 'Prata', price: 0 },
      { name: 'Rosê Gold', price: 0 },
      { name: 'Vermelho', price: 0 },
      { name: 'Branco', price: 0 },
      { name: 'Preto', price: 0 },
      { name: 'Rosa', price: 0 },
    ],
  },
  {
    id: 417,
    name: 'Menu de Comida',
    description: 'Cardápio de pratos e buffet personalizado. (Selecionar no ato da compra)',
    price: 2.00,
    category: 'casamento',
    subcategory: 'menu',
    image: '/images/menu.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Tamanho 10x15cm', price: 2.00 },
      { name: 'Tamanho 9x20cm', price: 3.50 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Kraft', price: 0 },
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Couchê Brilho', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Matte (Fosco)', price: 0 },
    ],
  },
  {
    id: 418,
    name: 'Menu de Bebida',
    description: 'Cardápio de drinks e bebidas personalizado.',
    price: 3.50,
    category: 'casamento',
    subcategory: 'menu',
    image: '/images/menu bar.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Tamanho 9x20cm', price: 3.50 },
      { name: 'Tamanho 21x29cm', price: 15.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Offset', price: 0 },
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Kraft', price: 0 },
    ],
  },
  {
    id: 101,
    name: 'Polaroid Mini',
    description: 'Polaroid tamanho mini (5x7cm), ideal para carteira ou decoração delicada.',
    price: 1.25,
    category: 'fotos',
    subcategory: 'polaroide',
    image: '/images/WhatsApp Image 2026-04-06 at 14.57.00 (2).jpeg',
  },
  {
    id: 102,
    name: 'Polaroid Clássica',
    description: 'O formato clássico (7x10cm) que todo mundo ama, com espaço para legenda.',
    price: 3.00,
    category: 'fotos',
    subcategory: 'polaroide',
    image: '/images/WhatsApp Image 2026-04-06 at 14.57.00 (1).jpeg',
  },
  {
    id: 103,
    name: 'Polaroid Grande',
    description: 'Polaroid em tamanho maior (10x12cm) para destacar seus melhores momentos.',
    price: 6.00,
    category: 'fotos',
    subcategory: 'polaroide',
    image: '/images/WhatsApp Image 2026-04-06 at 14.57.01.jpeg',
    isNew: true,
  },
  {
    id: 104,
    name: 'Polaroid de Mesa',
    description: 'Polaroid tamanho 13x11cm colada em um suporte de mesa feito de MDF.',
    price: 12.00,
    category: 'fotos',
    subcategory: 'polaroide',
    image: '/images/WhatsApp Image 2026-04-06 at 14.57.00.jpeg',
    isNew: true,
  },
  {
    id: 2,
    name: 'Kit Fotos 3x4 Tradicional',
    description: 'Kit com 10 fotos 3x4 em papel fotográfico glossy de alta qualidade.',
    price: 5.00,
    category: 'fotos',
    subcategory: '3x4',
    image: imgFoto3x4_1,
    images: [imgFoto3x4_1, imgFoto3x4_2],
  },
  {
    id: 3,
    name: 'Revelação 10x15 Premium',
    description: 'Revelação de foto no tamanho clássico 10x15cm em papel fotográfico.',
    price: 8.00,
    category: 'fotos',
    subcategory: '10x15',
    image: imgFoto10x15_1,
    images: [imgFoto10x15_1, imgFoto10x15_2],
  },
  {
    id: 105,
    name: 'Revelação Fotográfica A5',
    description: 'Revelação de alta resolução em tamanho A5 (15x21cm).',
    price: 12.00,
    category: 'fotos',
    subcategory: 'a5',
    image: imgFotoA5_1,
    images: [imgFotoA5_1, imgFotoA5_2],
    isNew: true,
  },
  {
    id: 106,
    name: 'Revelação Fotográfica A4',
    description: 'Ampliação fotográfica em tamanho A4 (21x30cm), perfeita para emoldurar.',
    price: 18.00,
    category: 'fotos',
    subcategory: 'a4',
    image: imgFotoA4_1,
    images: [imgFotoA4_1, imgFotoA4_2],
  },
  {
    id: 140,
    name: 'Sacola Almofada',
    description: 'Sacola em formato de almofada personalizada, ideal for brindes e mimos especiais.',
    price: 4.50,
    category: 'sacolas',
    subcategory: 'sacola-almofada',
    image: imgSacolaAlmofada,
  },
  {
    id: 13,
    name: 'Sacola de Papel Vertical',
    description: 'Sacola de papel personalizada vertical, ideal para presentes e mimos.',
    price: 8.50,
    category: 'sacolas',
    subcategory: 'sacola-vertical',
    image: imgSacolaVertical,
    isFeatured: true,
    variations: [
      { name: 'PP', price: 3.50 },
      { name: 'P', price: 4.50 },
      { name: 'M', price: 6.00 },
      { name: 'G', price: 8.50 },
    ],
  },
  {
    id: 14,
    name: 'Sacola de Papel Horizontal',
    description: 'Sacola de papel personalizada horizontal, ideal para presentes e mimos.',
    price: 4.50,
    category: 'sacolas',
    subcategory: 'sacola-horizontal',
    image: imgSacolaHorizontal,
    variations: [
      { name: 'PP', price: 3.50 },
      { name: 'P', price: 4.50 },
      { name: 'M', price: 6.00 },
      { name: 'G', price: 8.50 },
    ],
  },
  {
    id: 15,
    name: 'Caixa Pirâmide Personalizada',
    description: 'Caixa em formato de pirâmide decorada para festas e eventos.',
    price: 4.50,
    category: 'caixas',
    subcategory: 'piramide',
    image: imgCaixaPiramide,
    isNew: true,
  },
  {
    id: 16,
    name: 'Caixa Milk',
    description: 'Caixa milk personalizada, clássica e versátil para festas.',
    price: 5.00,
    category: 'caixas',
    subcategory: 'milk',
    image: imgCaixaMilk,
  },
  {
    id: 301,
    name: 'Caixa Lanchinho',
    description: 'Caixa lanchinho ideal para kits lanches e lembrancinhas.',
    price: 5.00,
    category: 'caixas',
    subcategory: 'lanchinho',
    image: imgCaixaLanchinho,
  },
  {
    id: 302,
    name: 'Caixa Canudo',
    description: 'Caixa com suporte para canudo, um charme extra na sua festa.',
    price: 6.00,
    category: 'caixas',
    subcategory: 'caixa-canudo',
    image: imgCaixaCanudo,
  },
  {
    id: 303,
    name: 'Caixa Maletinha',
    description: 'Caixa formato maletinha, prática e decorativa.',
    price: 6.00,
    category: 'caixas',
    subcategory: 'maletinha',
    image: imgCaixaMaletinha,
  },
  {
    id: 304,
    name: 'Caixa Almofada',
    description: 'Caixa em formato de almofada, perfeita para mimos delicados.',
    price: 4.50,
    category: 'caixas',
    subcategory: 'almofada',
    image: imgCaixaAlmofada,
  },
  {
    id: 305,
    name: 'Caixa Cenário',
    description: 'Embalagem de luxo com cenário 3D temático para decoração.',
    price: 15.00,
    category: 'caixas',
    subcategory: 'caixa-cenario',
    image: imgCaixaCenario,
  },
  {
    id: 306,
    name: 'Caixa para Docinho',
    description: 'Caixa personalizada para docinhos gourmet (1 a 4 unidades).',
    price: 2.50,
    category: 'caixas',
    subcategory: 'caixa-docinho',
    image: imgCaixaDocinho,
    variations: [
      { name: 'caixa para 1', price: 2.50 },
      { name: 'caixa para 2', price: 3.50 },
      { name: 'caixa para 3', price: 5.00 },
      { name: 'caixa para 4', price: 6.00 },
    ],
  },
  {
    id: 307,
    name: 'Porta Caneta',
    description: 'Caixa porta caneta personalizada, útil e linda para festas.',
    price: 5.00,
    category: 'caixas',
    subcategory: 'porta-caneta',
    image: imgCaixaPortaCaneta,
  },
  {
    id: 308,
    name: 'Porta Chaveiro',
    description: 'Caixa expositora para chaveiros e pequenos mimos personalizados.',
    price: 6.00,
    category: 'caixas',
    subcategory: 'porta-chaveiro',
    image: imgCaixaPortaChaveiro,
  },
  {
    id: 309,
    name: 'Porta Sabonete',
    description: 'Caixa delicada para sabonetes ou mimos artesanais.',
    price: 5.00,
    category: 'caixas',
    subcategory: 'porta-sabonete',
    image: imgCaixaPortaSabonete,
  },
  {
    id: 310,
    name: 'Caixa Cubo',
    description: 'Caixa em formato de cubo, moderna e minimalista.',
    price: 4.50,
    category: 'caixas',
    subcategory: 'cubo',
    image: imgCaixaCubo,
  },
  {
    id: 311,
    name: 'Cachepô',
    description: 'Cachepô personalizado para guloseimas ou pequenos vasos.',
    price: 3.00,
    category: 'caixas',
    subcategory: 'cachepo',
    image: imgCaixaCachepo,
  },
  {
    id: 312,
    name: 'Centro de Mesa',
    description: 'Peça central para mesa de convidados, completa a decoração.',
    price: 9.00,
    category: 'caixas',
    subcategory: 'centro-mesa',
    image: imgCaixaCentroMesa,
  },
  {
    id: 313,
    name: 'Porta Bis',
    description: 'Suporte personalizado para chocolate Bis (Simples ou Duplo).',
    price: 4.50,
    category: 'caixas',
    subcategory: 'porta-bis',
    image: imgCaixaPortaBis,
    variations: [
      { name: 'Porta Bis', price: 4.50 },
      { name: 'Porta Bis Duplo', price: 5.50 },
    ],
  },
  {
    id: 314,
    name: 'Caixa Mc Donalds',
    description: 'Caixa estilo fast food, divertida e espaçosa.',
    price: 7.00,
    category: 'caixas',
    subcategory: 'mc-donalds',
    image: imgCaixaMcDonalds,
  },
  {
    id: 315,
    name: 'Porta Tubete',
    description: 'Suporte personalizado para tubete de acrílico.',
    price: 3.50,
    category: 'caixas',
    subcategory: 'porta-tubete',
    image: imgCaixaPortaTubete,
  },
  {
    id: 112,
    name: 'Caixa 15x13x4',
    description: 'Caixa personalizada no tamanho 15x13x4cm, ideal para kits e presentes.',
    price: 7.00,
    category: 'caixas',
    subcategory: '15x13x4',
    image: imgCaixa15x13x4_1,
    images: [imgCaixa15x13x4_1, imgCaixa15x13x4],
    isNew: true,
  },
  {
    id: 113,
    name: 'Caixa 10x9',
    description: 'Caixa personalizada no tamanho 10x9cm, perfeita para pequenos presentes.',
    price: 6.00,
    category: 'caixas',
    subcategory: '10x9',
    image: imgCaixa10x9_1,
  },
  {
    id: 114,
    name: 'Caixa 9x4x2',
    description: 'Mini caixa personalizada no formato 9x4x2cm, ideal for doces e lembrancinhas.',
    price: 4.00,
    category: 'caixas',
    subcategory: '9x4x2',
    image: imgCaixa9x4x2_1, images: [imgCaixa9x4x2_1, imgCaixa9x4x2_2]
  },
  {
    id: 17,
    name: 'Etiqueta Redonda Personalizada',
    description: 'Kit com 10 unidades. Escolha o tamanho ideal para sua marca.',
    price: 6.50,
    category: 'etiquetas',
    subcategory: 'redonda',
    image: imgLabelRound1,
    images: [imgLabelRound1, imgLabelRound2, imgLabelRound3],
    isNew: true,
    variations: [
      { name: '2x2', price: 6.50 },
      { name: '3x3', price: 8.50 },
      { name: '4x4', price: 11.00 },
      { name: '5x5', price: 12.00 },
      { name: '6x6', price: 14.00 },
    ],
  },
  {
    id: 18,
    name: 'Etiqueta Quadrada Minimalista',
    description: 'Kit com 10 unidades. Escolha o tamanho ideal para sua embalagem.',
    price: 6.50,
    category: 'etiquetas',
    subcategory: 'quadrada',
    image: imgEtiquetaQuadrada1,
    images: [imgEtiquetaQuadrada1, imgEtiquetaQuadrada2],
    variations: [
      { name: '2x2', price: 6.50 },
      { name: '3x3', price: 8.50 },
      { name: '4x4', price: 11.00 },
      { name: '5x5', price: 12.00 },
      { name: '6x6', price: 14.00 },
    ],
  },
  {
    id: 115,
    name: 'Etiqueta Retangular Personalizada',
    description: 'Kit com 10 unidades. Perfeita para identificar e estilizar seus produtos',
    price: 15.00,
    category: 'etiquetas',
    subcategory: 'retangular',
    image: imgLabelRect1,
    images: [imgLabelRect1, imgLabelRect2, imgLabelRect3],
    variations: [
      { name: '4x10', price: 15.00 },
    ],
  },
  {
    id: 116,
    name: 'Etiqueta Caixão Personalizada',
    description: 'Kit com 10 unidades. Formato diferenciado para destacar sua marca.',
    price: 8.00,
    category: 'etiquetas',
    subcategory: 'caixao',
    image: imgEtiquetaCaixao,
    images: [imgEtiquetaCaixao],
    variations: [
      { name: '6x10', price: 8.00 },
    ],
  },
  {
    id: 316,
    name: 'Tag para Xuxinha',
    description: 'Tag personalizada: "Para seu cabelo não grudar no gloss". Acompanha xuxinha.',
    price: 3.00,
    category: 'etiquetas',
    subcategory: 'tag-xuxinha',
    image: imgTagXuxinha,
    isNew: true,
  },
  {
    id: 19,
    name: 'Adesivo Redondo Personalizado',
    description: 'Kit com 10 unidades. Perfeito para personalizar seus mimos e embalagens.',
    price: 6.50,
    category: 'adesivos',
    subcategory: 'redondo',
    image: imgAdesivoRedondo2, images: [imgAdesivoRedondo1, imgAdesivoRedondo2,
      imgAdesivoTransparente, imgAdesivoRedondo3],
    isNew: true,
    variations: [
      { name: '2x2', price: 6.50 },
      { name: '3x3', price: 8.50 },
      { name: '4x4', price: 11.00 },
      { name: '5x5', price: 12.00 },
      { name: '6x6', price: 14.00 },
    ],
  },
  {
    id: 20,
    name: 'Adesivo Quadrado Personalizado',
    description: 'Kit com 10 unidades. Ideal para lacres e identificação de produtos.',
    price: 6.50,
    category: 'adesivos',
    subcategory: 'quadrado',
    image: imgAdesivoQuadrado,
    images: [imgAdesivoQuadrado, imgAdesivoQuadradoTransparente],
    variations: [
      { name: '2x2', price: 6.50 },
      { name: '3x3', price: 8.50 },
      { name: '4x4', price: 11.00 },
      { name: '5x5', price: 12.00 },
      { name: '6x6', price: 14.00 },
    ],
  },
  {
    id: 21,
    name: 'Chaveiro Quadrado 3x4',
    description: 'Chaveiro em acrílico resistente com foto personalizada frente e verso.',
    price: 8.50,
    category: 'chaveiros',
    subcategory: 'acrilico-quadrado',
    image: imgChaveiroQuadrado1,
    images: [imgChaveiroQuadrado1, imgChaveiroQuadrado2],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 22,
    name: 'Chaveiro Redondo 3x4',
    description: 'Chaveiro redondo em acrílico cristal, perfeito para lembranças.',
    price: 10.00,
    category: 'chaveiros',
    subcategory: 'acrilico-redondo',
    image: imgChaveiroRedondo,
    images: [imgChaveiroRedondo, imgChaveiroRedondo2],
  },
  {
    id: 23,
    name: 'Cartão de Visita',
    description: 'A primeira impressão é a que fica. Cartão profissional para elevar a credibilidade',
    price: 35.00,
    category: 'cartoes',
    subcategory: 'visita',
    image: imgCartaoVisita1,
    images: [imgCartaoVisita1, imgCartaoVisita2],
    isNew: true,
    variations: [
      { name: '50 unidades', price: 35.00 },
    ],
  },
  {
    id: 24,
    name: 'Cartão de Agradecimento',
    description: 'O toque final perfeito para encantar e fidelizar seus clientes em cada entrega.',
    price: 15.00,
    category: 'cartoes',
    subcategory: 'agradecimento',
    image: imgCartaoAgradecimento,
    variations: [
      { name: '10 unidades', price: 15.00 },
    ],
  },
  {
    id: 118,
    name: 'Cartão Fidelidade',
    description: 'A melhor forma de recompensar e manter seus clientes sempre por perto.',
    price: 15.00,
    category: 'cartoes',
    subcategory: 'fidelidade',
    image: imgCartaoFidelidade,
    isNew: true,
    variations: [
      { name: '10 unidades', price: 15.00 },
    ],
  },
  {
    id: 119,
    name: 'Cartão Presente',
    description: 'Surpreenda quem você ama com um vale-presente personalizado e especial.',
    price: 15.00,
    category: 'cartoes',
    subcategory: 'presente',
    image: imgCartaoPresente,
    isNew: true,
    variations: [
      { name: '10 unidades', price: 15.00 },
    ],
  },
  {
    id: 121,
    name: 'Convite Digital Simples',
    description: 'Convite digital estático enviado em formato de imagem, ideal para WhatsApp.',
    price: 20.00,
    category: 'convites',
    subcategory: 'digital-simples',
    image: imgConviteDigital,
  },
  {
    id: 25,
    name: 'Convite Interativo',
    description: 'Convite digital com botões clicáveis para localização e confirmação de presença.',
    price: 35.00,
    category: 'convites',
    subcategory: 'interativo',
    image: imgConviteInterativoSub,
    images: [imgConviteInterativoSub, imgConviteInterativo1, imgConviteInterativo2, imgConviteInterativo3],
    isNew: true,
    isFeatured: true,
  },
  {
    id: 122,
    name: 'Convite PDF Longo',
    description: 'Convite em formato PDF com rolagem, permitindo incluir mais informações e fotos.',
    price: 50.00,
    category: 'convites',
    subcategory: 'pdf-longo',
    image: imgConvitePdfLongo,
  },
  {
    id: 26,
    name: 'Convite em Vídeo 1 Minuto',
    description: 'Vídeo personalizado de até 1 minuto para convidar seus amigos pelas redes sociais.',
    price: 65.00,
    category: 'convites',
    subcategory: 'video-1min',
    image: imgConviteVideo,
  },
  {
    id: 123,
    name: 'Convite em Vídeo +1 Minuto',
    description: 'Vídeo detalhado com mais de 1 minuto.',
    price: 75.00,
    category: 'convites',
    subcategory: 'video-plus-1min',
    image: imgConviteVideo,
  },
  {
    id: 27,
    name: 'Criação de Logomarca Profissional',
    description: 'Desenvolvimento de logomarca exclusiva com entrega de arquivos em vetor.',
    price: 65.00,
    category: 'outros',
    subcategory: 'logomarca',
    image: imgLogoDianaSantos,
    images: [imgLogoDianaSantos, imgLogoSolangeAlves, imgLogoKatiaNunes],
  },
  {
    id: 28,
    name: 'Identidade visual completa',
    description: 'Logomarca, paleta de cores, tipografia e guia de uso da marca.',
    price: 85.00,
    category: 'outros',
    subcategory: 'identidade-visual',
    image: imgIdentidadeVisualSamira,
    isNew: true,
  },
  {
    id: 29,
    name: 'Convite Individual 5x5',
    description: 'Convite individual impresso, ideal para controle de entrada em eventos.',
    price: 12.00,
    category: 'convites',
    subcategory: 'impresso',
    image: imgConviteIndividualSub,
    isNew: true,
    variations: [
      { name: 'Kit com 10', price: 12.00 },
    ],
  },
  {
    id: 124,
    name: 'Convite A5 Personalizado',
    description: 'Convite impresso em tamanho A5 (15x21cm) com design exclusivo para o seu evento.',
    price: 60.00,
    category: 'convites',
    subcategory: 'a5',
    image: imgA5,
    isNew: true,
  },
  {
    id: 126,
    name: 'Calendário Mini',
    description: 'Calendário de mesa personalizado em formato compacto',
    price: 6.00,
    category: 'outros',
    subcategory: 'calendario',
    image: imgCalendarioMini1,
    images: [imgCalendarioMini1, imgCalendarioMini2],
    isNew: true,
  },
  {
    id: 130,
    name: 'Calendário A4',
    description: 'Calendário personalizado em tamanho A4 com suas fotos favoritas',
    price: 15.00,
    category: 'outros',
    subcategory: 'calendario',
    image: imgCalendarioA4_1,
    images: [imgCalendarioA4_1, imgCalendarioA4_2],
    isNew: true,
  },
  {
    id: 127,
    name: 'Buquê de Borboletas',
    description: 'Buque de borboletas, iluminado, com 3 polaroides, selecione a cor apos a compra',
    price: 55.00,
    category: 'outros',
    subcategory: 'buque-borboletas',
    image: imgBuqueBorboletas,
    isNew: true,
    variations: [
      { name: 'P', price: 55.00 },
      { name: 'M', price: 70.00 },
      { name: 'G', price: 80.00 },
    ],
  },
  {
    id: 324,
    name: 'Buquê Van Gogh',
    description: 'Buque de borboletas azuis com girassois amarelos, 1 polaroide inclusa',
    price: 55.00,
    category: 'outros',
    subcategory: 'buque-borboletas',
    image: imgBuqueVanGogh,
    isNew: true,
    variations: [
      { name: 'P', price: 55.00 },
      { name: 'M', price: 70.00 },
      { name: 'G', price: 80.00 },
    ],
  },
  {
    id: 128,
    name: 'Kit Mini Ímã',
    description: 'Kit com 6 ímãs personalizados com suas fotos, alta qualidade de impressão.',
    price: 18.00,
    category: 'outros',
    subcategory: 'imas-geladeira',
    image: imgImaGeladeira1,
    images: [imgImaGeladeira1, imgImaGeladeira2],
    isNew: true,
  },
  {
    id: 325,
    name: 'Ímã Polaroide',
    description: 'Ímã 8x9 personalizado no estilo polaroide.',
    price: 6.00,
    category: 'outros',
    subcategory: 'imas-geladeira',
    image: imgImaGeladeira1,
    isNew: true,
  },
  {
    id: 326,
    name: 'Ímã de Geladeira',
    description: 'Ímã 8x9 personalizado com sua foto preferida.',
    price: 7.00,
    category: 'outros',
    subcategory: 'imas-geladeira',
    image: imgImaGeladeira2,
    isNew: true,
  },
  {
    id: 129,
    name: 'Kit só um bolinho',
    description: 'Combo com diversos itens personalizados para tornar sua festa inesquecível.',
    price: 80.00,
    category: 'outros',
    subcategory: 'kit-festa',
    image: imgKitFesta,
    isNew: true,
    variations: [
      { name: 'Sem display de mesa', price: 80.00 },
      { name: 'Com display de mesa', price: 95.00 },
    ],
  },
  {
    id: 317,
    name: 'Cofre Personalizado',
    description: 'Cofre personalizado no tema da sua preferencia. Pedido mínimo 10 unidades.',
    price: 4.00,
    category: 'outros',
    subcategory: 'cofre',
    image: imgCofre,
    isNew: true,
    minQuantity: 10,
    variations: [
      { name: 'Sem cofre', price: 4.00 },
      { name: 'Com cofre', price: 6.50 },
    ],
  },
  {
    id: 318,
    name: 'Aplique para Tubete',
    description: 'Apliques em papel glossy personalizados no seu tema.',
    price: 1.50,
    category: 'outros',
    subcategory: 'aplique-tubete',
    image: imgApliqueTubete,
    isNew: true,
  },
  {
    id: 319,
    name: 'Kit Corporativo',
    description: 'Kit com Sacola personalizada, caneta e bloco de notas',
    price: 18.00,
    category: 'outros',
    subcategory: 'kit-corporativo',
    image: imgKitCorporativo,
    isNew: true,
  },
  {
    id: 320,
    name: 'Porta Docinhos Personalizado',
    description: 'Forminhas decoradas para docinhos gourmet, kit com 25 unidades.',
    price: 15.00,
    category: 'outros',
    subcategory: 'porta-docinho',
    image: imgPortaDocinho,
    isNew: true,
  },
  {
    id: 321,
    name: 'Painel Lambe Lambe',
    description: 'Painel em papel glossy a4, estilo lambe lambe, personalizado.',
    price: 45.00,
    category: 'outros',
    subcategory: 'lambe-lambe',
    image: imgLambeLambe,
    isNew: true,
    variations: [
      { name: '10 folhas', price: 45.00 },
      { name: '20 folhas', price: 90.00 },
      { name: '30 folhas', price: 130.00 },
      { name: '40 folhas', price: 175.00 },
      { name: '50 folhas', price: 215.00 },
    ],
  },
  {
    id: 322,
    name: 'Caderno Personalizado A5',
    description: 'Caderno de anotações tamanho A5 com capa dura personalizada no seu tema.',
    price: 6.00,
    category: 'outros',
    subcategory: 'caderno',
    image: imgCadernoA5,
    isNew: true,
    variations: [
      { name: 'Apenas frente ou verso', price: 6.00 },
      { name: 'Frente e verso', price: 14.00 },
      { name: 'Frente, verso e guarda', price: 26.00 },
    ],
    secondaryVariationTitle: 'Opções de caderno:',
    secondaryVariations: [
      { name: 'Sem caderno', price: 0 },
      { name: 'Com caderno', price: 8.00 },
    ],
  },
  {
    id: 327,
    name: 'Caderno Personalizado Brochurao',
    description: 'Caderno estilo brochurão com capa personalizada no seu tema preferido.',
    price: 12.00,
    category: 'outros',
    subcategory: 'caderno',
    image: imgCaderno,
    isNew: true,
    variations: [
      { name: 'Apenas frente ou verso', price: 12.00 },
      { name: 'Frente e verso', price: 26.00 },
      { name: 'Frente, verso e guarda', price: 50.00 },
    ],
    secondaryVariationTitle: 'Opções de caderno:',
    secondaryVariations: [
      { name: 'Sem caderno', price: 0 },
      { name: 'Com caderno', price: 12.00 },
    ],
  },
  {
    id: 328,
    name: 'Caderno Personalizado Espiral',
    description: 'Caderno espiral com capa dura e personalizada no seu tema.',
    price: 12.00,
    category: 'outros',
    subcategory: 'caderno',
    image: imgCadernoEspiral,
    isNew: true,
    variations: [
      { name: 'Apenas frente ou verso', price: 12.00 },
      { name: 'Frente e verso', price: 24.00 },
      { name: 'Frente, verso e guarda', price: 48.00 },
    ],
    secondaryVariationTitle: 'Opções de caderno:',
    secondaryVariations: [
      { name: 'Sem caderno', price: 0 },
      { name: 'Com caderno 1 Matéria', price: 15.00 },
      { name: 'Com caderno 10 Matérias', price: 30.00 },
    ],
  },
  {
    id: 323,
    name: 'Formas de dizer Eu Te Amo',
    description: 'livreto ilustrado, formas de dizer eu te amo.',
    price: 40.00,
    category: 'outros',
    subcategory: 'livreto',
    image: imgLivreto,
    isNew: true,
    variations: [
      { name: 'Marvel', price: 40.00 },
      { name: 'Disney', price: 40.00 },
      { name: 'Personalizado', price: 40.00 },
    ],
    secondaryVariationTitle: 'Sacola personalizada:',
    secondaryVariations: [
      { name: 'Sem sacola personalizada', price: 0 },
      { name: 'Com sacola personalizada', price: 5.00 },
    ],
  },
  {
    id: 141,
    name: 'Kit Manhã',
    description: 'Kit com xícara, mini coador e quadro personalizados.',
    price: 95.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixas-personalizadas',
    image: '/images/kit_manha_gen.png',
    isNew: true,
  },
  {
    id: 142,
    name: 'Kit Relax',
    description: 'Kit com escalda pés lavanda, óleo de banho e hidratante.',
    price: 35.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixas-personalizadas',
    image: '/images/kit_relax_gen.png',
    isNew: true,
  },
  {
    id: 143,
    name: 'Kit Skin Care',
    description: 'Kit com esfoliante, máscara hidratante, hidratante labial e argila branca.',
    price: 45.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixas-personalizadas',
    image: '/images/kit_skincare_gen.png',
    isNew: true,
    isFeatured: true,
  },
  {
    id: 146,
    name: 'Quadro Personalizado',
    description: 'Quadro personalizado com fotos + brinde ímã polaroide.',
    price: 40.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 13.41.30.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 147,
    name: 'Kit Bela',
    description: 'Embalagem personalizada + colar e brinco.',
    price: 70.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixas-personalizadas',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.37 (1).jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 150,
    name: 'Caixa de Memórias',
    description: 'Caixa personalizada com 8 polaroides 5x6.',
    price: 15.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixas-personalizadas',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.38 (6).jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 153,
    name: 'Kit Unha',
    description: 'Caixinha personalizada com esmalte e lixa de unha.',
    price: 18.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixas-personalizadas',
    image: '/images/WhatsApp Image 2026-04-06 at 14.28.58.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 148,
    name: 'Foto Imã Calendário',
    description: 'Linda foto com ímã em formato de calendário tamanho 10x15, personalizada.',
    price: 20.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.38 (4).jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 149,
    name: 'Balas Personalizadas',
    description: 'Balas personalizadas temas variados (kit com 3 un).',
    price: 5.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.38 (5).jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 151,
    name: 'Caneca Acrílica Personalizada',
    description: 'Personalize a caneca com o tema que preferir.',
    price: 30.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.38.jpeg',
    isNew: true,
    noPaper: true,
    secondaryVariationTitle: 'Cor da Caneca',
    secondaryVariations: [
      { name: 'Branco', price: 0 },
      { name: 'Preto', price: 0 },
      { name: 'Rosa', price: 0 },
      { name: 'Amarelo', price: 0 },
    ]
  },
  {
    id: 152,
    name: 'Chaveiro 3x4 Personalizado',
    description: 'Chaveiro transparente tamanho 3x4, personalizado com fotos frente e verso.',
    price: 10.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 14.01.52.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 154,
    name: 'Sacola Presenteável',
    description: 'Sacola de papel personalizada vertical, ideal para presentes e mimos.',
    price: 8.50,
    category: 'dia-dos-namorados',
    subcategory: 'embalagens-personalizadas',
    image: '/images/WhatsApp Image 2026-04-06 at 14.29.00.jpeg',
    isNew: true,
    variations: [
      { name: 'PP', price: 3.50 },
      { name: 'P', price: 4.50 },
      { name: 'M', price: 6.00 },
      { name: 'G', price: 8.50 },
    ],
  },
  {
    id: 155,
    name: 'Caixinha Personalizada',
    description: 'Caixa ideal para embalar mimos e presentes pequenos com todo carinho.',
    price: 9.00,
    category: 'dia-dos-namorados',
    subcategory: 'embalagens-personalizadas',
    image: '/images/WhatsApp Image 2026-04-06 at 14.29.16.jpeg',
    isNew: true,
  },
  {
    id: 156,
    name: 'Caixa Buquê Especial Casamento',
    description: 'Um presente sofisticado para madrinhas ou decoração da mesa dos noivos.',
    price: 45.00,
    category: 'casamento',
    subcategory: 'lembrancinhas-casamento',
    image: '/images/WhatsApp Image 2026-04-06 at 14.38.29 (1).jpeg',
    isNew: true,
    isFeatured: true,
    noPaper: true,
    variations: [
      { name: 'Com 8 bombons', price: 45.00 },
      { name: 'Com flores', price: 55.00 },
      { name: 'Com maquiagem (valor a definir)', price: 0.00 },
    ],
    secondaryVariationTitle: 'Opção de Cor:',
    secondaryVariations: [
      { name: 'Branco/Pérola', price: 0 },
      { name: 'Dourado', price: 0 },
      { name: 'Rosê Gold', price: 0 },
      { name: 'Vermelho', price: 0 },
      { name: 'Azul Serenity', price: 0 },
    ]
  },
  {
    id: 158,
    name: 'Buquê de Borboletas (Wedding Edition)',
    description: 'Buquê iluminado com borboletas, perfeito para o pré-wedding ou daminhas.',
    price: 55.00,
    category: 'casamento',
    subcategory: 'lembrancinhas-casamento',
    image: imgBuqueBorboletas,
    isNew: true,
    noPaper: true,
    secondaryVariationTitle: 'Opção de Cor:',
    secondaryVariations: [
      { name: 'Branco Clássico', price: 0 },
      { name: 'Azul Serenity', price: 0 },
      { name: 'Rosa Quartzo', price: 0 },
      { name: 'Dourado', price: 0 },
      { name: 'Marsala', price: 0 },
    ],
    variations: [
      { name: 'P', price: 55.00 },
      { name: 'M', price: 70.00 },
      { name: 'G', price: 80.00 },
    ],
  },
  {
    id: 144,
    name: 'Card Brincos',
    description: 'Card personalizado acompanhado de um lindo par de brincos de pérola.',
    price: 5.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.36 (1).jpeg',
    isNew: true,
  },
  {
    id: 145,
    name: 'Card Manteiga de Cacau',
    description: 'Card personalizado com uma manteiga de cacau também personalizada.',
    price: 8.00,
    category: 'dia-dos-namorados',
    subcategory: 'mimos',
    image: '/images/WhatsApp Image 2026-04-06 at 13.25.36 (2).jpeg',
    isNew: true,
  },
  {
    id: 503,
    name: 'Caixa para Ovo de Páscoa',
    description: 'Caixa resistente e com berço adaptado para ovo de colher ou tradicional.',
    price: 10.00,
    category: 'pascoa',
    subcategory: 'caixas-personalizadas',
    image: '/images/caixas_ovo_tematicas.jpg',
    isNew: true,
  },
  {
    id: 504,
    name: 'Card com 1 Bombom',
    description: 'Card personalizado com suporte para 1 bombom. Um mimo doce e acessível.',
    price: 4.00,
    category: 'pascoa',
    subcategory: 'mimos',
    image: '/images/card_1_bombom_pascoa.jpg',
    isNew: true,
  },
  {
    id: 505,
    name: 'Card com 1 Batom',
    description: 'Card tematico para encaixar um chocolate tipo Batom.',
    price: 3.50,
    category: 'pascoa',
    subcategory: 'mimos',
    image: '/images/card_batom_pascoa.jpg',
    isNew: true,
  },
  {
    id: 506,
    name: 'Card com 1 Bis',
    description: 'Um pequeno gesto de carinho: card personalizado com 1 chocolate Bis.',
    price: 2.50,
    category: 'pascoa',
    subcategory: 'mimos',
    image: '/images/card_1_bis_pascoa.jpg',
    isNew: true,
  },
  {
    id: 507,
    name: 'Caça aos Ovos',
    description: 'Kit completo com pistas e pegadas para uma caça ao ovos inesquecivel.',
    price: 15.00,
    category: 'pascoa',
    subcategory: 'mimos',
    image: '/images/caca_aos_ovos_completo.jpg',
    isNew: true,
  },
  {
    id: 508,
    name: 'Tag para Lembrancinha',
    description: 'Tags personalizadas para pendurar em ovos de páscoa ou saquinhos de doces.',
    price: 2.50,
    category: 'pascoa',
    subcategory: 'mimos',
    image: '/images/tag_lembrancinha_pascoa.jpg',
    isNew: true,
  },
  {
    id: 509,
    name: 'Card com Moeda de Chocolate',
    description: 'Divertido card com uma moeda de chocolate dourada. O tesouro da Páscoa!',
    price: 3.50,
    category: 'pascoa',
    subcategory: 'mimos',
    image: '/images/card_moeda_pix.jpg',
    isNew: true,
  },
  {
    id: 510,
    name: 'Caixa Cenário',
    description: 'Embalagem luxuosa com cenário 3D temático.',
    price: 40.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/caixa_cenario_pascoa.jpg',
    isNew: true,
  },
  {
    id: 511,
    name: 'Sacola para Ovo',
    description: 'Sacola reforçada para ovos de páscoa.',
    price: 14.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/caixas_ovo_tematicas.jpg',
    isNew: true,
  },
  {
    id: 512,
    name: 'Sacola para Bombom',
    description: 'Sacola ideal para bombons ou mini ovos.',
    price: 9.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/sacola_bombom_mimo.jpg',
    isNew: true,
  },
  {
    id: 513,
    name: 'Coelhinho com 3 Bis',
    description: 'Embalagem de coelho com 3 unidades de Bis.',
    price: 10.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/coelhinho_3_bis.jpg',
    isNew: true,
  },
  {
    id: 514,
    name: 'Maletinha para 3 Ovinhos 50g',
    description: 'Maletinha para 3 mini ovinhos de 50g.',
    price: 16.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/maletinha_3_ovos.jpg',
    isNew: true,
  },
  {
    id: 515,
    name: 'Kitkat Personalizado',
    description: 'Capa personalizada para chocolate Kitkat.',
    price: 10.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/kitkat_personalizado.jpg',
    isNew: true,
  },
  {
    id: 516,
    name: 'Barra de Chocolate Personalizado',
    description: 'Rótulo personalizado para barras de 90g/100g.',
    price: 18.00,
    category: 'pascoa',
    subcategory: 'embalagens-personalizadas',
    image: '/images/barra_chocolate_personalizada.jpg',
    isNew: true,
  },
  {
    id: 517,
    name: 'Buquê de Borboleta com Bombom',
    description: 'Buquê de borboletas iluminado com bombons inclusos.',
    price: 45.00,
    category: 'pascoa',
    subcategory: 'buques',
    image: '/images/buque_borboleta_ouro_branco.jpg',
    isNew: true,
    variations: [
      { name: 'P (10 borboletas + 4 bombons)', price: 45.00 },
      { name: 'M (25 borboletas + 6 bombons)', price: 65.00 },
      { name: 'G (40 borboletas + 10 bombons)', price: 80.00 },
    ],
  },
  {
    id: 518,
    name: 'Caixa Buquê',
    description: 'Caixa buquê personalizada, com apoio para bombom.',
    price: 40.00,
    category: 'pascoa',
    subcategory: 'buques',
    image: '/images/caixa_buque_sonho_valsa.jpg',
    isNew: true,
    variations: [
      { name: 'P (6 bombons)', price: 40.00 },
      { name: 'M (12 bombons)', price: 55.00 },
      { name: 'G (24 bombons)', price: 85.00 },
    ],
  },
  {
    id: 519,
    name: 'Buquê Coração',
    description: 'Buquê em formato de coração especial para Páscoa.',
    price: 20.00,
    category: 'pascoa',
    subcategory: 'buques',
    image: '/images/buque_coracao_urso.jpg',
    isNew: true,
    variations: [
      { name: 'Sonho de Valsa', price: 20.00 },
      { name: 'Ouro Branco', price: 20.00 },
      { name: 'Serenata do Amor', price: 20.00 },
      { name: 'Personalizado', price: 20.00 },
    ],
  },
  {
    id: 220,
    name: 'Certidão de Namoro',
    description: 'Um registro oficial do seu amor! Certidão personalizada com os dados do casal.',
    price: 10.00,
    category: 'dia-dos-namorados',
    subcategory: 'certidao-namoro',
    image: '/images/certidao.jpeg',
    isNew: true,
    variations: [
      { name: '14x20', price: 10.00 },
      { name: '21x29', price: 22.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Offset', price: 0 },
    ],
  },
  {
    id: 221,
    name: 'Caixa Envelope',
    description: 'Surpreenda com esta linda caixa envelope! Acompanha mimos sortidos.',
    price: 18.00,
    category: 'dia-dos-namorados',
    subcategory: 'caixa-envelope',
    image: '/images/caixa envelope.jpeg',
    isNew: true,
    noPaper: true,
    variations: [
      { name: 'Tamanho P', price: 18.00 },
      { name: 'Tamanho M', price: 27.00 },
      { name: 'Tamanho G', price: 40.00 },
    ],
  },
  {
    id: 222,
    name: 'Kit Cinema',
    description: 'Um kit completo para uma noite de cinema especial. Acompanha guloseimas.',
    price: 80.00,
    category: 'dia-dos-namorados',
    subcategory: 'kit-cinema',
    image: '/images/kit cinema.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 223,
    name: 'Uno do Amor',
    description: 'O jogo que você já conhece, agora com cartas personalizadas para o casal!',
    price: 45.00,
    category: 'dia-dos-namorados',
    subcategory: 'uno-amor',
    image: '/images/uno do amor.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 224,
    name: 'Cartão Pop Up',
    description: 'Um cartão surpreendente que ganha vida ao abrir! Perfeito para declarar seu amor.',
    price: 35.00,
    category: 'dia-dos-namorados',
    subcategory: 'cartao-popup',
    image: '/images/popup.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 225,
    name: 'Tickets do Amor',
    description: 'Vales personalizados para momentos especiais! Um presente criativo.',
    price: 25.00,
    category: 'dia-dos-namorados',
    subcategory: 'tickets',
    image: '/images/ticket.jpeg',
    isNew: true,
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Offset', price: 0 },
    ],
  },
  {
    id: 226,
    name: '10 Músicas sobre Nós',
    description: 'Uma seleção especial de músicas que marcaram a história do casal. Um presente sonoro e inesquecível!',
    price: 20.00,
    category: 'dia-dos-namorados',
    subcategory: '10-musicas-nos',
    image: '/images/10musicas.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 227,
    name: 'Site dos Noivos Personalizado',
    description: 'Site completo com lista de presentes e confirmação de presença.',
    price: 150.00,
    category: 'casamento',
    subcategory: 'site-dos-noivos',
    image: '/images/site noivos.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 228,
    name: 'Monograma Personalizado',
    description: 'Monograma exclusivo com as iniciais dos noivos.',
    price: 25.00,
    category: 'casamento',
    subcategory: 'monograma',
    image: '/images/monograma.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 229,
    name: 'Identidade Visual Completa',
    description: 'Logomarca, paleta de cores e tipografia para o seu casamento.',
    price: 95.00,
    category: 'casamento',
    subcategory: 'identidade-visual',
    image: '/images/id visual.jpeg',
    isNew: true,
    noPaper: true,
  },
  {
    id: 230,
    name: 'Placa Reservado Personalizada',
    description: 'Placas personalizadas para reserva de mesas.',
    price: 10.00,
    category: 'casamento',
    subcategory: 'placa-reservado',
    image: '/images/reservado.jpeg',
    isNew: true,
    variations: [
      { name: 'Kit com 2 unidades', price: 10.00 },
      { name: 'Kit com 4 unidades', price: 16.00 },
      { name: 'Kit com 5 unidades', price: 22.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Couchê Brilho', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Kraft', price: 0 },
    ],
  },
  {
    id: 231,
    name: 'Placa Numerada Personalizada',
    description: 'Placas numeradas para identificação de mesas com elegância.',
    price: 25.00,
    category: 'casamento',
    subcategory: 'placa-numerada',
    image: '/images/placa numero.jpeg',
    isNew: true,
    variations: [
      { name: 'Kit com 5 unidades', price: 25.00 },
      { name: 'Kit com 10 unidades', price: 50.00 },
    ],
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Matte (Fosco)', price: 0 },
      { name: 'Glossy (Brilho)', price: 0 },
      { name: 'Kraft', price: 0 },
      { name: 'Couchê Fosco', price: 0 },
      { name: 'Couchê Brilho', price: 0 },
    ],
  },
  {
    id: 419,
    name: 'Kit com 2 Cadernos de Votos',
    description: 'Par de cadernos personalizados para o momento dos votos.',
    price: 25.00,
    category: 'casamento',
    subcategory: 'caderno-de-votos',
    image: '/images/aderno de votos.jpeg',
    isNew: true,
    secondaryVariationTitle: 'Tipo de Papel:',
    secondaryVariations: [
      { name: 'Offset', price: 0 },
      { name: 'Ofício', price: 0 },
    ],
  },
];
